prev_commit_message_error: !!!SEE PREVIOUS COMMIT CHANGES!!! Fiddle with chess_game's border (which is currently a separate class, not an inner-class, from the actual class that draws the board and tokens). Wanted to move the Player whoseTurn displayer from being inside the board (blue and yellow drawn Tiles) to the border, but unsuccessful in getting this field to refresh its value after MouseEvents are fired. I think the solution is to include the border in the class that draws the board and tokens, then add another variable to represent the (((offset))) x and y distance of the border before drawing the board and tokens. Also changed some minor String output to the console within the mouseClicked()'s if-else blocks that regulate token selection and new token destination selection.